pumukit_paella_player_parent:
    resource: "../../../../pumukit/pumukit/src/Pumukit/BasePlayerBundle/Controller/"
    type:     annotation
    prefix:   /

pumukit_paella_player:
    resource: "@PumukitPaellaPlayerBundle/Controller/"
    type:     annotation
    prefix:   /
